// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edwilmbikmoxdarlhbjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkd2lsbWJpa21veGRhcmxoYmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDE3MDcsImV4cCI6MjA1ODk3NzcwN30.NrSPsORh37qkqqFvziFZiWh0CaPPfFaaLdRJffxV9uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);